#!/usr/bin/env node
/**
 * Generate tokens/colors.css and tokens/tailwind.css from the DTCG token JSON.
 *
 *   node scripts/build-tokens.mjs          write the files
 *   node scripts/build-tokens.mjs --check  verify they are up to date, write nothing
 *
 * Source of truth is tokens/primitive.json + tokens/semantic.{dark,light}.json,
 * in the DTCG Design Tokens Format Module 2025.10. The CSS is output — never edit it.
 *
 * Node only, no dependencies. Same posture as scripts/render-og.sh: a committed
 * command you run by hand, not a build step anything installs.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = (n) => JSON.parse(readFileSync(join(root, 'tokens', n), 'utf8'));

const prim = T('primitive.json');
const dark = T('semantic.dark.json');
const light = T('semantic.light.json');

const px = (d) => (d.value === 0 ? '0' : `${d.value}${d.unit}`);
const c255 = (n) => Math.round(n * 255);
const alias = (path) => `var(--fk-${path.split('.').slice(1).join('-')})`;

// A family name containing a space must be quoted in CSS.
const family = (n) => (/\s/.test(n) ? `'${n}'` : n);

function val(v) {
  if (typeof v === 'string' && v.startsWith('{')) return alias(v.slice(1, -1));
  if (typeof v === 'string') return family(v);
  if (typeof v === 'number') return String(v);
  // fontFamily is an array of strings; a multi-shadow is an array of objects.
  if (Array.isArray(v)) {
    return v.every((x) => typeof x === 'string')
      ? v.map(family).join(', ')
      : v.map(shadow).join(',\n                    ');
  }
  if (v?.colorSpace) {
    const [r, g, b] = v.components.map(c255);
    return v.alpha !== undefined ? `rgba(${r}, ${g}, ${b}, ${v.alpha})` : v.hex;
  }
  if (v?.offsetX) return shadow(v);
  if (v?.unit) return px(v);
  return String(v);
}
const shadow = (s) =>
  `${px(s.offsetX)} ${px(s.offsetY)} ${px(s.blur)} ${px(s.spread)} ${val(s.color)}`;

function* decls(group) {
  for (const [k, v] of Object.entries(group ?? {})) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) yield [k, val(v.$value)];
  }
}

const pad = (rows) => {
  const w = Math.max(...rows.map(([n]) => n.length));
  return rows.map(([n, v]) => `${n.padEnd(w)} ${v};`);
};

const roleRows = (set, prefix = '') => {
  const rows = [];
  for (const [k, v] of decls(set.color)) {
    if (k === 'on-accent' || k === 'green-3-override') continue;
    rows.push([`${prefix}--${k}:`, v]);
  }
  for (const [k, v] of decls(set.shadow)) rows.push([`${prefix}--shadow-${k}:`, v]);
  return rows;
};

// ── colors.css ─────────────────────────────────────────────────────────────
const lightGreen3 = val(light.color['green-3-override'].$value);
const ind = (lines, n) => lines.map((l) => ' '.repeat(n) + l).join('\n');

let css = `/**
 * Fukuii Brand — Color tokens
 *
 * GENERATED by scripts/build-tokens.mjs from tokens/primitive.json and
 * tokens/semantic.{dark,light}.json. Do not hand-edit — change the JSON
 * and regenerate, or the two will drift.
 *
 * Colors derived from fukuii-hex-logo.png (pixel-sampled 2026-06-20).
 */

:root {
  /* Palette — raw brand values. Prefer a role token in components. */
${ind(pad([...decls(prim.color)].map(([k, v]) => [`--fk-${k}:`, v])), 2)}

  /* Role tokens — dark, the default theme. */
${ind(pad(roleRows(dark)), 2)}

  /* Semantic signal — not part of the raw palette. */
${ind(pad([...decls(prim.signal)].map(([k, v]) => [`--color-${k}:`, v])), 2)}
}

/* Light theme, explicitly selected. */
[data-theme="light"] {
${ind(pad([['--fk-green-3:', lightGreen3], ...roleRows(light)]), 2)}
}

/* Light theme from OS preference, when none is explicitly set. :not([data-theme])
   keeps an explicit choice winning over the OS. Must match the block above. */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${ind(pad([['--fk-green-3:', lightGreen3], ...roleRows(light)]), 4)}
  }
}
`;

// ── tailwind.css ───────────────────────────────────────────────────────────
const themeRows = [
  ...[...decls(prim.color)].map(([k]) => [`--color-fk-${k}:`, `var(--fk-${k})`]),
  ...[...decls(dark.color)]
    .filter(([k]) => k !== 'green-3-override')
    .map(([k]) => [`--color-${k}:`, `var(--${k})`]),
];
const fontRows = [...decls(prim.font)].map(([k, v]) => [`--font-${k}:`, v]);

let tw = `/**
 * Fukuii Brand — Tailwind CSS 4 @theme block
 *
 * GENERATED by scripts/build-tokens.mjs. Do not hand-edit.
 *
 * Registers the palette and role tokens as Tailwind utilities, so a consumer can
 * write bg-fk-green-3, text-accent, border-border-strong. Re-exports colors.css
 * through var(), so it holds no values of its own and needs no edit when a color
 * changes. Nothing here compiles it — consuming repos do.
 */

@import './colors.css';

@theme {
${ind(pad(themeRows), 2)}

${ind(pad(fontRows), 2)}
}
`;

// ── write or check ─────────────────────────────────────────────────────────
const targets = [
  ['tokens/colors.css', css],
  ['tokens/tailwind.css', tw],
];

if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [rel, want] of targets) {
    const got = readFileSync(join(root, rel), 'utf8');
    if (got === want) console.log(`  ok     ${rel}`);
    else { console.log(`  STALE  ${rel} — regenerate with: node scripts/build-tokens.mjs`); stale++; }
  }
  console.log(stale ? '\n  RESULT: token CSS is out of date with the JSON.' : '\n  RESULT: generated CSS matches the JSON.');
  process.exit(stale ? 1 : 0);
}

for (const [rel, out] of targets) {
  writeFileSync(join(root, rel), out);
  console.log('  wrote', rel);
}
